# Generated by Django 4.2.7 on 2025-11-19 12:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_despacho', models.IntegerField(default=1)),
                ('estado', models.CharField(choices=[('despacho', 'Despacho'), ('re_despacho', 'Re-despacho')], default='despacho', max_length=20)),
                ('resultado', models.CharField(blank=True, choices=[('entregado', 'Entregado'), ('no_disponible', 'No Disponible'), ('error', 'Error')], max_length=20, null=True)),
                ('foto_entrega', models.ImageField(blank=True, null=True, upload_to='fotos_entregas/')),
                ('observaciones', models.TextField(blank=True)),
                ('coordenadas_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('coordenadas_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Despacho',
                'verbose_name_plural': 'Despachos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=10, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('año', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900)])),
                ('color', models.CharField(max_length=30)),
                ('cilindrada', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('kilometraje', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('en_uso', 'En Uso'), ('mantenimiento', 'Mantenimiento'), ('fuera_servicio', 'Fuera de Servicio')], default='disponible', max_length=20)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultimo_mantenimiento', models.DateField(blank=True, null=True)),
                ('proximo_mantenimiento', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Moto',
                'verbose_name_plural': 'Motos',
                'ordering': ['patente'],
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=200)),
                ('direccion', models.TextField()),
                ('telefono_cliente', models.CharField(max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10)),
                ('tipo', models.CharField(choices=[('receta_detendida', 'Receta Detenida'), ('normal', 'Normal')], default='normal', max_length=20)),
                ('estado_actual', models.CharField(choices=[('retiro_receta', 'Retiro de Receta'), ('traslado', 'Traslado'), ('despacho', 'Despacho'), ('re_despacho', 'Re-despacho')], default='retiro_receta', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Órdenes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('entregas_totales', models.IntegerField(default=0)),
                ('entregas_exitosas', models.IntegerField(default=0)),
                ('entregas_fallidas', models.IntegerField(default=0)),
                ('tiempo_promedio', models.DurationField(blank=True, null=True)),
                ('ingresos_dia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(blank=True, max_length=12, null=True)),
                ('telefono', models.CharField(max_length=20)),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('coordinador', 'Coordinador'), ('repartidor', 'Repartidor')], default='repartidor', max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_usuarios/')),
                ('estado_turno', models.CharField(choices=[('disponible', 'Disponible'), ('ocupado', 'Ocupado'), ('descanso', 'Descanso')], default='disponible', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('moto', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_asignado', to='core.moto')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('zona', models.CharField(max_length=100)),
                ('vehiculo', models.CharField(blank=True, max_length=100)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ordenes', models.ManyToManyField(blank=True, related_name='rutas', to='core.orden')),
                ('repartidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas', to='core.usuarioprofile')),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='OrdenMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('retiro_receta', 'Retiro de Receta'), ('traslado', 'Traslado'), ('despacho', 'Despacho'), ('re_despacho', 'Re-despacho')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('despacho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='core.despacho')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='core.orden')),
                ('repartidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='core.usuarioprofile')),
            ],
            options={
                'verbose_name': 'Movimiento de Orden',
                'verbose_name_plural': 'Movimientos de Órdenes',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='orden',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_asignadas', to='core.usuarioprofile'),
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=200)),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('observaciones', models.TextField(blank=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='core.orden')),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='despacho',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despachos', to='core.orden'),
        ),
        migrations.AddField(
            model_name='despacho',
            name='repartidor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despachos', to='core.usuarioprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='despacho',
            unique_together={('orden', 'numero_despacho')},
        ),
    ]
