# Generated by Django 4.2.7 on 2025-11-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioprofile',
            name='fecha_inicio_descanso',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que inició el descanso', null=True),
        ),
    ]
