# Generated by Django 4.2.7 on 2025-11-19 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuarioprofile_fecha_inicio_descanso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
                ('ciudad', models.CharField(default='Santiago', max_length=100)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Farmacia',
                'verbose_name_plural': 'Farmacias',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='orden',
            name='farmacia_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_destino', to='core.farmacia', verbose_name='Farmacia Destino'),
        ),
        migrations.AddField(
            model_name='orden',
            name='farmacia_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_origen', to='core.farmacia', verbose_name='Farmacia Origen'),
        ),
    ]
